version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis:latest
    command: redis-server /etc/redis-1.conf
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis-1.conf:/etc/redis-1.conf"
      - "./data/redis-master:/data/redis"
    networks:
      - sentinelnet
  redis-slave1:
    container_name: "redis-slave1"
    image: redis:latest
    command: redis-server /etc/redis-2.conf --slaveof redis-master 6379
    ports:
      - "6380:6379"
    volumes:
      - "./redis/redis-2.conf:/etc/redis-2.conf"  
      - "./data/redis-slave1:/data/redis"
    depends_on:
      - redis-master
    networks:
      - sentinelnet
  redis-slave2:
    container_name: "redis-slave2"
    image: redis:latest
    command: redis-server /etc/redis-3.conf --slaveof redis-master 6379
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    volumes:
      - "./redis/redis-3.conf:/etc/redis-3.conf"
      - "./data/redis-slave2:/data/redis"
    networks:
      - sentinelnet
  redis-sentinel1:
    container_name: 'redis-sentinel1'
    image: redis:latest
    command: redis-server /etc/config/redis-sentinel-1.conf --sentinel
    ports:
      - "26379:26379"
    volumes:
      - "./sentinel:/etc/config"
      - "./data/sentinel1:/data/redis"
    networks:
      - sentinelnet
  redis-sentinel2:
    container_name: 'redis-sentinel2'
    image: redis:latest
    command: redis-server /etc/config/redis-sentinel-2.conf --sentinel
    ports:
      - "26380:26379"
    volumes:
      - "./sentinel:/etc/config"
      - "./data/sentinel2:/data/redis"
    networks:
      - sentinelnet
  redis-sentinel3:
    container_name: 'redis-sentinel3'
    image: redis:latest
    command: redis-server /etc/config/redis-sentinel-3.conf --sentinel
    ports:
      - "26381:26379"
    volumes:
      - "./sentinel:/etc/config"
      - "./data/sentinel3:/data/redis"
    networks:
      - sentinelnet

networks:
  sentinelnet:
    driver: bridge